temp_path:    '/var/tmp/rec-sys-client'
weights_path: '/home/adrian/development/personal/maestria/thesis-paper/rec-sys-client-lib/weights'
api:
  host: 'http://nonosoft.ddns.net:8000'
  token: 'e3ff025094fe0ee474501bbeda0a2a44e80230c1'
