name: recsys-client-lib
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - seaborn
    - matplotlib
    - numpy=1.21
    - pandas
    - jupyterlab
    - ipywidgets
    - pymysql
    - mysql-connector-python
    - tqdm
    - bunch
    - pyyaml
    - sphinx
    - sphinx_rtd_theme
    - scikit-learn
    - scikit-surprise
    - pip
    - pip:
        - apache-airflow
        - --extra-index-url https://download.pytorch.org/whl/cu116
        - torch==1.12.1+cu116
        - simple-rest-client
        - sentence-transformers
        - singleton-decorator
        - parallel-pandas
