# Generated by Django 4.1 on 2022-10-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('image', models.CharField(max_length=255, verbose_name='Image URL')),
            ],
        ),
    ]
