# Generated by Django 4.1 on 2022-10-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0013_user_ai_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistancesMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DistancesMatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(db_column='row')),
                ('column', models.IntegerField(db_column='column')),
                ('value', models.FloatField()),
                ('matrix', models.ForeignKey(db_column='distances_matrix_id', on_delete=django.db.models.deletion.DO_NOTHING, to='recsysweb.distancesmatrix')),
            ],
        ),
    ]
