# Generated by Django 4.1 on 2022-11-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0014_similarity_matrix_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='popularity',
            field=models.FloatField(default=0, verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(max_length=500, verbose_name='Name'),
        ),
    ]
