# Generated by Django 4.1 on 2022-11-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0015_item_popularity_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['popularity'], name='recsysweb_i_popular_c79b81_idx'),
        ),
    ]
