# Generated by Django 4.1 on 2022-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0016_item_recsysweb_i_popular_c79b81_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritymatrix',
            name='type',
            field=models.IntegerField(choices=[(1, 'User To User'), (2, 'Item To Item')], default=1),
        ),
    ]
