# Generated by Django 4.1 on 2022-12-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0017_similaritymatrix_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaritymatrix',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
