# Generated by Django 4.1 on 2022-12-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0018_alter_similaritymatrix_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritymatrixcell',
            name='version',
            field=models.FloatField(default=0),
        ),
    ]
