# Generated by Django 4.1 on 2022-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0019_similaritymatrixcell_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similaritymatrixcell',
            name='version',
        ),
        migrations.AddField(
            model_name='similaritymatrix',
            name='verison',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='similaritymatrixcell',
            name='verison',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='similaritymatrixcell',
            index=models.Index(fields=['verison'], name='recsysweb_s_verison_a3e755_idx'),
        ),
    ]
