# Generated by Django 4.1 on 2022-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0020_remove_similaritymatrixcell_version_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='similaritymatrixcell',
            name='recsysweb_s_verison_a3e755_idx',
        ),
        migrations.RenameField(
            model_name='similaritymatrix',
            old_name='verison',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='similaritymatrixcell',
            old_name='verison',
            new_name='version',
        ),
        migrations.AddIndex(
            model_name='similaritymatrixcell',
            index=models.Index(fields=['version'], name='recsysweb_s_version_1ae8ba_idx'),
        ),
    ]
