# Generated by Django 4.1 on 2022-12-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0021_remove_similaritymatrixcell_recsysweb_s_verison_a3e755_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('item_similarity_matrix', models.ForeignKey(db_column='item_similarity_matrix_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_item_similarity_matrix_id', to='recsysweb.similaritymatrix', verbose_name='Item Similarity Matrix')),
                ('user_similarity_matrix', models.ForeignKey(db_column='user_similarity_matrix_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_similarity_matrix_id', to='recsysweb.similaritymatrix', verbose_name='User Similarity Matrix')),
            ],
        ),
    ]
