# Generated by Django 4.1 on 2022-12-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0022_recommender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='item',
            name='votes',
            field=models.FloatField(default=0, verbose_name='Votes'),
        ),
    ]
