# Generated by Django 4.1 on 2022-12-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0023_item_rating_item_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='max_items_by_similar_user',
            field=models.FloatField(default=10, verbose_name='Max Items by Similar Users'),
        ),
        migrations.AddField(
            model_name='recommender',
            name='max_similar_users',
            field=models.FloatField(default=10, verbose_name='Max Similar Users'),
        ),
    ]
