# Generated by Django 4.1 on 2022-12-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0024_recommender_max_items_by_similar_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='max_items_by_similar_user',
            field=models.IntegerField(default=10, verbose_name='Max Items by Similar Users'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='max_similar_users',
            field=models.IntegerField(default=10, verbose_name='Max Similar Users'),
        ),
    ]
