# Generated by Django 4.1 on 2022-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0025_alter_recommender_max_items_by_similar_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position in Recommendations View'),
        ),
    ]
