# Generated by Django 4.1 on 2022-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0027_recommender_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
    ]
