# Generated by Django 4.1 on 2022-12-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0028_alter_item_description_alter_recommender_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Description'),
        ),
    ]
