# Generated by Django 4.1 on 2022-12-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0029_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='max_similar_items',
            field=models.IntegerField(default=10, verbose_name='Max Similar Items'),
        ),
    ]
