# Generated by Django 4.1 on 2022-12-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0030_recommender_max_similar_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommender',
            options={'permissions': [('info', 'Show recommender debug information')]},
        ),
    ]
