# Generated by Django 4.1 on 2022-12-29 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0032_alter_recommender_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommender',
            options={'permissions': (('info', 'Show recommender debug information'), ('reset_interactions', 'Reset User Interactions'))},
        ),
    ]
