# Generated by Django 4.1 on 2023-01-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0034_item_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderEnsemple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(default='', max_length=5000, verbose_name='Description')),
                ('position', models.IntegerField(default=1, verbose_name='Position in Recommendations View')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
            ],
        ),
        migrations.AddField(
            model_name='recommender',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='similaritymatrix',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='RecommenderEnsembleConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_user_iterations', models.IntegerField(default=10, verbose_name='Max User Iterations')),
                ('recommender', models.ForeignKey(db_column='recommender_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_recommender_id', to='recsysweb.similaritymatrix', verbose_name='Recommender')),
            ],
        ),
    ]
