# Generated by Django 4.1 on 2023-01-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0035_recommenderensemple_recommender_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommenderEnsemple',
            new_name='RecommenderEnsemble',
        ),
    ]
