# Generated by Django 4.1 on 2023-01-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0036_rename_recommenderensemple_recommenderensemble'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='type',
            field=models.IntegerField(choices=[(1, 'Populars'), (2, 'New Populars'), (3, 'Collavorative Filtering'), (4, 'Uset Profile')], default=3),
        ),
    ]
