# Generated by Django 4.1 on 2023-01-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0039_alter_recommenderensembleconfig_recommender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommenderensembleconfig',
            name='max_user_iterations',
        ),
        migrations.AddField(
            model_name='recommenderensembleconfig',
            name='active_from_n_user_iterations',
            field=models.IntegerField(default=0, verbose_name='Active from n user interactions'),
        ),
        migrations.AddField(
            model_name='recommenderensembleconfig',
            name='active_to_n_user_iterations',
            field=models.IntegerField(default=0, verbose_name='Active to n user interactions'),
        ),
    ]
