# Generated by Django 4.1 on 2023-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0041_alter_recommender_item_similarity_matrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='max_items_by_similar_user',
            field=models.IntegerField(default=0, verbose_name='Max Items by Similar Users'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='max_similar_items',
            field=models.IntegerField(default=0, verbose_name='Max Similar Items'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='max_similar_users',
            field=models.IntegerField(default=0, verbose_name='Max Similar Users'),
        ),
    ]
