# Generated by Django 4.1 on 2023-01-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0042_alter_recommender_max_items_by_similar_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='item_similarity_matrix',
            field=models.ForeignKey(blank=True, db_column='item_similarity_matrix_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_item_similarity_matrix_id', to='recsysweb.similaritymatrix', verbose_name='Item Similarity Matrix'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='user_similarity_matrix',
            field=models.ForeignKey(blank=True, db_column='user_similarity_matrix_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_similarity_matrix_id', to='recsysweb.similaritymatrix', verbose_name='User Similarity Matrix'),
        ),
    ]
