# Generated by Django 4.1 on 2023-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0044_recommenderensembleconfig_ensemble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
