# Generated by Django 4.1 on 2023-01-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0047_recommenderensempleevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderensembleconfig',
            name='n_items_by_session',
            field=models.IntegerField(default=5, verbose_name='Number of items to evaluate by session'),
        ),
        migrations.AlterField(
            model_name='recommenderensempleevaluation',
            name='ensemble',
            field=models.ForeignKey(db_column='ensemble_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_ensemble_id', to='recsysweb.recommenderensemble', unique=True, verbose_name='Recommender Ensemble'),
        ),
        migrations.AddIndex(
            model_name='recommenderensempleevaluation',
            index=models.Index(fields=['enable'], name='recsysweb_r_enable_5547f0_idx'),
        ),
    ]
