# Generated by Django 4.1 on 2023-01-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0048_recommenderensembleconfig_n_items_by_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='suitable_to_train',
            field=models.BooleanField(default=True, verbose_name='Suitable to train'),
        ),
    ]
