# Generated by Django 4.1 on 2023-01-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0049_interaction_suitable_to_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderensempleevaluation',
            name='mean_window_size',
            field=models.FloatField(default=5),
        ),
    ]
