# Generated by Django 4.1 on 2023-01-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0050_recommenderensempleevaluation_mean_window_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommenderensempleevaluation',
            name='mean_window_size',
            field=models.IntegerField(default=5),
        ),
    ]
