# Generated by Django 4.1 on 2023-01-25 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0053_alter_recommenderensempleevaluation_mean_window_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderensempleevaluationmetric',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
