# Generated by Django 4.1 on 2023-01-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0054_recommenderensempleevaluationmetric_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommender',
            options={'permissions': (('info', 'Show recommender debug information'), ('reset_interactions', 'Reset User Interactions'), ('api_management', 'API Management'), ('airflow_management', 'Airflow Management'))},
        ),
    ]
