@startuml
title Deployment

actor User

cloud "Hosting Cloud" #palegreen {
    node RecSys <<Web App & REST API>>
    database RecSysDB <<MySQL>>
}

cloud "Computing Cloud" #palegreen {
    node Airflow <<Job Scheduler>> #FEFECE {
        artifact [SVDSimJob]
        artifact [NFMSimJob]
        artifact [BertSimJob]
    }
    database AirflowDB <<MySQL>>
}


User -r-> RecSys: See & Make Recs
RecSys -[#blue,dotted,thickness=2]-> SVDSimJob: Interactions
RecSys <-[#green,dotted,thickness=2]- SVDSimJob: Update SimMatrix
RecSys -[#blue,dotted,thickness=2]-> NFMSimJob: Interactions
RecSys <-[#green,dotted,thickness=2]- NFMSimJob: Update SimMatrix


RecSys -[#blue,dotted,thickness=2]-> BertSimJob: Interactions
RecSys <-[#green,dotted,thickness=2]- BertSimJob: Update SimMatrix


RecSys <-[dotted,thickness=1]-> RecSysDB
Airflow <-[dotted,thickness=1]-> AirflowDB
@enduml