@startuml
class RecommenderEnsempleEvaluation {
    - id: int
    - enable: bool
    - ensemble: RecommenderEnsemble
}

class RecommenderEnsempleEvaluationMetric {
    - evaluation: RecommenderEnsempleEvaluation
    - user: User
    - value: float
}

@enduml